### ISSUE TITLE
Please allow Catogram to be available via the official F-Droid repository.

### ISSUE THREAD

**Issue by 42837531** [Catogram/Catogram#76]
Unfortunately, without permission from the creator or official manager of Catogram, Catogram cannot be available via the official F-Droid repository, and there does not appear to be an official respository for Catogram that is for F-Droid either. For those of us that love Catogram but do not, or cannot, use the Google Play Store for reasons such as geopolitical trade wars, this would be immensely helpful.

**Comment by ctwoon** [comment]
Hm, you can download catogram from our channel: t.me/catogram

**Comment by ctwoon** [comment]
At my leisure I've read the f-droid policy, found that our application doesn't fit their requirements because we use Google services.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/Catogram/Catogram/issues/76#issuecomment-796807845

Which of the services that are provided by Google are utilised by Catogram? I understand why Firebase may be used, but the developers of the official distribution of Telegram are able to easily remove it for their builds that are for F-Droid, so that should not be problematic. Google Maps is also replaced by OpenStreetMap, which I believe is a much better alternative. I cannot think of anything else that may be required but analytic services, which should be optional anyway because some persons' devices cannot function well when many analytic services are running simultaneously.

Therefore, if the developers of Telegram can do it, why can you not?

**Comment by iTaysonLab** [comment]
@BEEDELLROKEJULIANLOCKHART Hello!

We won’t switch from Firebase to microG permanently - because of more reliable pushes system.

However, you can make a FOSS fork and upload, leaving Catogram name and developer references.

Anyway, if FDroid allows building from specific branch - I’d look into it. But FDroid is a pain to configure and add your app to it.

**Comment by ctwoon** [comment]
> Which of the services that are provided by Google are utilised by Catogram?

firebase, google payment system, maps and ota system (was used earlier)

firebase isn't going to be removed as without it to get notifications you need to run app in background which is bad for battery

> I cannot think of anything else that may be required but analytic services

we don't have them

about fdroid: 
as far as i know you can't just upload your own apk to fdroid, app are being built on their servers so you need to do many things  to configure it. both of the developers are students and we don't really have time to spend it on this. 

i think question closed?
